FIND_PATH(ALLEGRO_INCLUDE_DIR allegro.h /usr/include /usr/local/include)

FIND_LIBRARY(ALLEGRO_LIBRARY NAMES alleg PATH /usr/lib /usr/local/lib)

IF (ALLEGRO_INCLUDE_DIR AND ALLEGRO_LIBRARY)
   SET(ALLEGRO_FOUND TRUE)
ENDIF (ALLEGRO_INCLUDE_DIR AND ALLEGRO_LIBRARY)


IF (ALLEGRO_FOUND)
   IF (NOT Allegro_FIND_QUIETLY)
      MESSAGE(STATUS "Found Allegro: ${ALLEGRO_LIBRARY}")
   ENDIF (NOT Allegro_FIND_QUIETLY)
ELSE (ALLEGRO_FOUND)
   IF (Allegro_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Allegro")
   ENDIF (Allegro_FIND_REQUIRED)
ENDIF (ALLEGRO_FOUND)
